services:
  # 1. Redis (메시지 브로커 및 캐싱)
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - ws
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # 2. Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
    # ${환경변수명} 문법은 OS 환경변수 혹은 .env에서 해당 환경변수명과 일치하는 항목이 있으면 대입합니다.
    # 반드시 사전에 .env에 해당 항목이 존재하는지 확인해야 합니다.
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DB_EXPOSE_PORT}:${DB_PORT}
    networks:
      - ws
    volumes:
      - mysql_data:/var/lib/mysql  # 컨테이너가 삭제돼도 데이터는 호스트 파일시스템에 남음
    command: # 한글 저장을 위한 문자셋 설정 (필수!)
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --port=${DB_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. API Server (FastAPI)
  fastapi:
    container_name: fastapi
    image: ${DOCKER_USER}/${DOCKER_REPOSITORY}:app-${APP_VERSION}  # APP_VERSION은 빌드된 이미지의 버전관리를 위함입니다. v1.0.0 형식으로 사용합니다.
    env_file: .env
    volumes:
      - static_volume:/app/templates
      - media_volume:/app/media
    restart: always
    ports:
      - "8000:8000"
    networks:
      - ws
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # 4. AI Worker (Model 학습 및 추론)
  ai-worker:
    container_name: ai-worker
    image: ${DOCKER_USER}/${DOCKER_REPOSITORY}:ai-${AI_WORKER_VERSION}  # AI_WORKER_VERSION은 빌드된 이미지의 버전관리를 위함입니다. V1.0.0 형식으로 사용합니다.
    env_file: .env
    restart: always
    mem_limit: 4G
    networks:
      - ws
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # 5. Nginx (웹 서버 - 요청 리버스 프록시로 전달)
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ws
    depends_on:
      - fastapi

  # 6. certbot: SSL 인증서 발급담당
  certbot:
    image: certbot/certbot
    container_name: auto-certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 48h & wait $${!}; done;'"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  mysql_data:
    name: mysql_data
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume
  certbot-conf:
    name: certbot-conf
  certbot-www:
    name: certbot-www

networks:
  ws:
    name: ws
    driver: bridge
